#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Cloudflare Access (Managed OAuth) for the MCP worker. See #10 and
# docs/access.md, which this walks step for step.
#
# Nothing account-specific is baked in: this file is committed to a public
# repository, so every value is prompted for. What it collects lands in a
# gitignored .env as your record of the values; runtime configuration itself
# goes into the `vars` block of wrangler.jsonc IN YOUR FORK (correct there,
# never pushed upstream) — see .env.example.
#
# The order below is not the order the docs used to give, and the difference
# matters: Access is attached to the WORKER rather than to a hostname, and you
# cannot attach a Worker that does not exist yet. So the deploy comes first.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "imap-mcp — Cloudflare Access"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before we start"
say "This gates the MCP endpoint, which is read access to your whole mailbox."
say "It is the load-bearing control in this design, so it is worth doing slowly."
step "You need a Cloudflare account with Zero Trust enabled and an identity"
step "provider configured. The free plan covers 50 users."
step "You need a zone on that account to hang the hostname off."
step "You need Workers Paid — for the sync queues, not for Access."
note "Nothing here is irreversible, and nothing here is briefly open. The"
note "worker refuses every request Access did not authenticate for it, so a"
note "deploy without an Access application is a dead endpoint, not an open one."
confirm "Ready to go?" || exit 0

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
open_url "https://dash.cloudflare.com/"
step "Pick the account you'll deploy to, then open any zone's Overview."
step "The Account ID is in the right-hand sidebar under 'API'."
ask CLOUDFLARE_ACCOUNT_ID "Paste your Cloudflare account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Hostname"
say "Choose the hostname the MCP worker will answer on. It must be a zone on"
say "the account above."
note "Something like mail-mcp.example.com. This is the ROUTE only — Access"
note "attaches to the Worker itself, so it covers every route the Worker ever"
note "has, this one included."
ask MCP_ZONE_NAME "Zone name (e.g. example.com):"
ask MCP_ROUTE_PATTERN "Full hostname for the MCP endpoint:"
write_env MCP_ZONE_NAME "$MCP_ZONE_NAME"
write_env MCP_ROUTE_PATTERN "$MCP_ROUTE_PATTERN"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Deploy the Worker"
say "Access attaches to the Worker, and you cannot attach one that does not"
say "exist. So the Worker gets deployed first — with no audience tag yet."
say ""
warn "That is safe, and it is worth knowing why rather than trusting it:"
note "with ACCESS_AUD unset the worker requires the MCP_API_KEY secret as a"
note "bearer token (#35), and a deploy fails until that secret is set. There"
note "is no unauthenticated state to pass through."
say ""
note "wrangler.jsonc commits no database_id, so the first deploy provisions"
note "the D1 database and writes the id back into your checkout — keep it in"
note "your fork, and don't push it upstream. Queues needs a Workers Paid plan."
say ""
say "On a FIRST deploy the two required secrets ride along with the code:"
say "wrangler refuses to deploy without them, and 'wrangler secret put'"
say "cannot target a Worker that does not exist yet. So, in order:"
say ""
printf '  cat > .secrets.env <<DONE        # gitignored\n'
printf '  IMAP_PASSWORD=<app-specific password>\n'
printf '  MCP_API_KEY=<output of: openssl rand -base64 32>\n'
printf '  DONE\n'
printf '  pnpm exec wrangler deploy --secrets-file .secrets.env\n'
printf '  rm .secrets.env\n'
printf '  pnpm run db:migrate:remote\n'
say ""
step "Later deploys are plain 'pnpm run deploy'; rotate a secret with"
step "'pnpm exec wrangler secret put <NAME>'. The schema apply is a no-op"
step "if re-run."
say ""
confirm "Worker deployed?" || exit 0

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the Access application"
open_url "https://one.dash.cloudflare.com/"
say "Access controls -> Applications -> Add an application -> Self-hosted."
say "The dashboard wants these in this order:"
say ""
step "1. Destinations -> 'Add Workers' -> pick imap-mcp."
note "   Not a public hostname. Attaching the Worker is what Cloudflare calls"
note "   the safest way to gate one: it covers every route, Custom Domain and"
note "   workers.dev URL at once, rather than the single URL you name."
step "2. Leave the application name alone — it defaults once the"
step "   destination is set."
step "3. Access policies -> Create new policy -> Allow, one rule,"
step "   Emails -> your own address."
warn "   No Bypass policy on this application."
step "4. Authentication -> turn OFF 'Accept all available identity"
step "   providers', then select your identity provider explicitly."
say ""
say "Then the Additional settings tab — this is the step everything depends on:"
step "5. Turn ON 'Managed OAuth'."
step "6. Allow localhost clients and loopback clients (Claude Code"
step "   redirects to a loopback address)."
step "7. Add https://claude.ai/api/mcp/auth_callback to the allowed"
step "   redirect URIs (the claude.ai custom connector)."
step "8. Access token lifetime 5-15 minutes; session duration 1-2 weeks."
warn "Without Managed OAuth, a non-browser client gets a 302 it cannot follow"
warn "instead of a 401 it can act on, and no MCP client will connect at all."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Audience tag, route, and re-deploy"
step "Still on the Additional settings tab, copy the"
step "'Application Audience (AUD) Tag'. It is a long hex string."
warn "It must be THIS application's tag."
note "Every application in one Zero Trust account shares a tenant, so the"
note "audience is the only thing that tells them apart -- and the worker pins"
note "it. A token for another of your applications is refused here, which is"
note "exactly the point."
ask ACCESS_AUD "Paste the Application Audience tag:"
write_env ACCESS_AUD "$ACCESS_AUD"
say ""
say "That is everything. Add ACCESS_AUD (and your route, if you chose one)"
say "to the vars block of wrangler.jsonc in your fork, then re-deploy:"
say ""
printf '  pnpm run deploy\n'
printf '  curl -sSD- -o /dev/null https://%s/mcp\n' "$MCP_ROUTE_PATTERN"
say ""
step "Expect 401 with a www-authenticate header, and NO location header."
step "A 302 means Managed OAuth is still off -- go back to stage 5."
say ""
note "That curl passes whether or not the gate works, though: a request with no"
note "Access context is refused either way. The check that actually proves it"
note "is connecting Claude Code and running a search once signed in. If a"
note "SIGNED-IN user gets 401, ctx.access is not reaching the worker."
note "docs/access.md has the full list."

finish
