#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Cloudflare Access (Managed OAuth) for the MCP worker. See #10 and
# docs/access.md, which this walks step for step.
#
# Nothing account-specific is baked in: this file is committed to a public
# repository, so every value is prompted for. What it collects lands in a
# gitignored .env; the two that the worker actually reads are then pasted into
# your own copy of packages/mcp/wrangler.jsonc, which is committed and must not
# carry them upstream.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "imap-mcp — Cloudflare Access"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before we start"
say "This gates the MCP endpoint, which is read access to your whole mailbox."
say "It is the load-bearing control in this design, so it is worth doing slowly."
step "You need a Cloudflare account with Zero Trust enabled and an identity"
step "provider configured. The free plan covers 50 users."
step "You need a zone on that account to hang the hostname off."
step "You need Workers Paid — for the sync worker's queues, not for Access."
note "Nothing here is irreversible. Deleting the Access application later"
note "leaves the endpoint closed, not open: the worker verifies the token"
note "itself and refuses anything it cannot verify."
confirm "Ready to go?" || exit 0

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
open_url "https://dash.cloudflare.com/"
step "Pick the account you'll deploy to, then open any zone's Overview."
step "The Account ID is in the right-hand sidebar under 'API'."
ask CLOUDFLARE_ACCOUNT_ID "Paste your Cloudflare account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Hostname"
say "Choose the hostname the MCP worker will answer on. It must be a zone on"
say "the account above, and it is also the hostname the Access application"
say "will protect — the two have to match exactly."
note "Something like mail-mcp.example.com. Not a workers.dev hostname:"
note "an Access application cannot cover one, which is why workers_dev stays"
note "false in packages/mcp/wrangler.jsonc."
ask MCP_ZONE_NAME "Zone name (e.g. example.com):"
ask MCP_ROUTE_PATTERN "Full hostname for the MCP endpoint:"
write_env MCP_ZONE_NAME "$MCP_ZONE_NAME"
write_env MCP_ROUTE_PATTERN "$MCP_ROUTE_PATTERN"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Zero Trust team domain"
open_url "https://one.dash.cloudflare.com/"
step "If this is a fresh Zero Trust tenant, you'll be asked to choose a team"
step "name now. Whatever you pick becomes <team>.cloudflareaccess.com."
step "Otherwise: Settings -> Custom Pages shows your team domain."
warn "Include the https:// scheme, and no trailing slash."
note "It is compared to the token's 'iss' byte for byte, so a stray slash"
note "rejects every token with an error that reads like a signature problem."
ask ACCESS_TEAM_DOMAIN "Team domain (https://<team>.cloudflareaccess.com):"
write_env ACCESS_TEAM_DOMAIN "$ACCESS_TEAM_DOMAIN"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the Access application"
open_url "https://one.dash.cloudflare.com/"
step "Access controls -> Applications -> Add an application -> Self-hosted."
step "Application name: imap-mcp"
step "Public hostname: $MCP_ROUTE_PATTERN"
step "Add a policy: action Allow, one rule, Emails -> your own address."
warn "Make sure no Bypass policy exists on this hostname."
say ""
say "Then, under Advanced settings — this is the step everything depends on:"
step "Turn ON 'Managed OAuth'."
step "Turn on 'Allow localhost clients' and 'Allow loopback clients'"
step "  (Claude Code redirects to a loopback address)."
step "Add https://claude.ai/api/mcp/auth_callback to the allowed redirect"
step "  URIs (the claude.ai custom connector)."
step "Access token lifetime 5-15 minutes; session duration 1-2 weeks."
warn "Without Managed OAuth, a non-browser client gets a 302 it cannot follow"
warn "instead of a 401 it can act on, and no MCP client will connect at all."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Application Audience tag"
step "Open the application you just made -> Overview tab."
step "Copy the 'Application Audience (AUD) Tag'. It is a long hex string."
warn "It must be THIS application's tag."
note "Every application in one Zero Trust account is signed by the same keys,"
note "so the audience is the only thing that tells them apart — and the worker"
note "pins it. A validly-signed token for another of your applications is"
note "refused here, which is exactly the point."
ask ACCESS_AUD "Paste the Application Audience tag:"
write_env ACCESS_AUD "$ACCESS_AUD"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Wire it up and deploy"
say "Add these to your own copy of packages/mcp/wrangler.jsonc."
warn "That file is committed to a public repository. These values are yours:"
warn "do not push them upstream."
say ""
printf '  "vars": {\n'
printf '    "ACCESS_TEAM_DOMAIN": "%s",\n' "$ACCESS_TEAM_DOMAIN"
printf '    "ACCESS_AUD": "%s"\n' "$ACCESS_AUD"
printf '  },\n'
printf '  "routes": [{ "pattern": "%s", "custom_domain": true }]\n' "$MCP_ROUTE_PATTERN"
say ""
step "Leave workers_dev and preview_urls at false."
say ""
confirm "Added them?" || exit 0
say "Then deploy, and check it from the outside:"
say ""
printf '  pnpm --filter @imap-mcp/mcp run deploy\n'
printf '  curl -sSD- -o /dev/null https://%s/mcp\n' "$MCP_ROUTE_PATTERN"
say ""
step "Expect 401 with a www-authenticate header, and NO location header."
step "A 302 means Managed OAuth is still off — go back to stage 5."
note "docs/access.md has the rest of the checks, including the one that"
note "proves the worker verifies the token rather than trusting the edge."

finish
